### ISSUE TITLE
Determine what's going on with 40017 with `weather_fips`

### ISSUE THREAD

**Issue by geanders** [leighseverson/countyweather#14]
> testing this function with fips <- c(36081, 36085, 36087, 36119, 40017)-- values are missing for 40017 - this station doesn't have precipitation info? - Need to see how many of our fips codes will have missing values w/ this function. (SOME of the missing rows are because each month has 31 days)

**Comment by leighseverson** [comment]
It looks like weather data for 40017 doesn't have columns for TMIN or TMAX. When `weather_fips` is run with 40017 in a vector (`test <- weather_fips("40017", "36081")`) it returns missing values for the temperature columns. When weather_fips is run with 40017 alone (`weather_fips("40017")`) the function doesn't run and it returns the message `Error in eval(expr, envir, enclos) : object 'TMIN' not found`. 

Need to figure out how to let `weather_fips()` keep going even when there are missing columns. The problem comes up with the line `tot_dat <- dplyr::select(tot_dat, fips, id:month, col:TMIN)`.

**Comment by leighseverson** [comment]
Just tested this FIPS code - this problem isn't coming up anymore.
