### ISSUE TITLE
using SQL syntax in average_weather()

### ISSUE THREAD

**Issue by leighseverson** [leighseverson/countyweather#21]
I was s t r u g g l i n g to figure out how to get a `n_reporting` column in R - I need to figure out how to do this without SQL syntax.

**Comment by geanders** [comment]
I'd recommend doing the averaging across monitors using `dplyr`. Then you can `group_by` the date and then use `mutate` to get the average value (use `mean()`, probably with `na.rm = TRUE`-- see other comments in the Issues) and to get the number of monitors reporting, which we could do using `sum(!is.na(prcp))`, for example. We can discuss tomorrow. Since we have multiple weather metrics we want to do this for, we may want to do some `tidyr` jujitsu to make things easier :)
